# latest file is at:
# https://github.com/QiYuTechOrg/pl/blob/main/images.toml
#
# or you can download from jsdelivr
# https://cdn.jsdelivr.net/gh/QiYuTechOrg/pl@main/images.toml
#

[c.gcc]
default = "qiyutech/gcc:v10.2.0p1"
"v10.1.0" = "qiyutech/gcc:v10.1.0p1"
"v10.2.0" = "qiyutech/gcc:v10.2.0p1"

[rust]
"v1.51.0" = "qiyutech/rust:v1.51.0p0"
"v1.50.0" = "qiyutech/rust:v1.50.0p0"

[php]
"v8.0.3" = "qiyutech/php:v8.0.3p0"

[python]
"v3.9" = "qiyutech/python:v3.9p0"
"v3.8" = "qiyutech/python:v3.8p0"
