# latest file is at:
# https://github.com/QiYuTechOrg/pl/blob/main/images.toml
#
# or you can download from jsdelivr
# https://cdn.jsdelivr.net/gh/QiYuTechOrg/pl@main/images.toml
#

[c.gcc]
default = "qiyutech/gcc:v11.1.0p8"
"v10.1.0" = "qiyutech/gcc:v10.1.0p8"
"v10.2.0" = "qiyutech/gcc:v10.2.0p8"
"v10.3.0" = "qiyutech/gcc:v10.3.0p8"
"v11.1.0" = "qiyutech/gcc:v11.1.0p8"

[rust]
"v1.52.0" = "qiyutech/rust:v1.52.0p8"
"v1.51.0" = "qiyutech/rust:v1.51.0p8"
"v1.50.0" = "qiyutech/rust:v1.50.0p8"

[php]
"v8.0.5" = "qiyutech/php:v8.0.5p8"
"v8.0.3" = "qiyutech/php:v8.0.3p8"

[python]
"v3.9" = "qiyutech/python:v3.9p8"
"v3.8" = "qiyutech/python:v3.8p8"

[node]
v16 = "qiyutech/node:v16p8"
v15 = "qiyutech/node:v15p8"
v14 = "qiyutech/node:v14p8"
