name: Node v16

on:
  push:
    branches: [ main ]
    paths:
      - "lang/node/v16/*"
      - ".github/workflows/py_v16.yaml"

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: node:v16p9
      BUILD_DIR: lang/node/v16
    steps:
      - uses: actions/checkout@v2

      - name: DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ env.BUILD_DIR }}
          file: ./${{ env.BUILD_DIR }}/Dockerfile
          push: true
          tags: |
            qiyutech/${{ env.IMAGE_NAME }}
            ghcr.io/qiyutechdev/${{ env.IMAGE_NAME }}
