name: php v8.0.3

on:
  push:
    branches: [ main ]
    paths:
      - "lang/php/v8.0.3/*"
      - ".github/workflows/php_v8.0.3.yaml"

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: php:v8.0.3p2
      BUILD_DIR: lang/php/v8.0.3
    steps:
      - uses: actions/checkout@v2

      - name: DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: AliYun
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALI_USERNAME }}
          password: ${{ secrets.ALI_TOKEN }}


      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ env.BUILD_DIR }}
          file: ./${{ env.BUILD_DIR }}/Dockerfile
          push: true
          tags: |
            qiyutech/${{ env.IMAGE_NAME }}
            ghcr.io/qiyutechdev/${{ env.IMAGE_NAME }}
            registry.cn-hangzhou.aliyuncs.com/qiyutech/${{ env.IMAGE_NAME }}
