name: Runner Test

on:
  push:
    branches: [ main ]
    paths:
      - "runner/**"
      - ".github/workflows/runner_test.yaml"

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: runner:dev
      BUILD_DIR: runner

    steps:
      - uses: actions/checkout@v2

      - name: Run Test
        run: |
          make test
