name: Runner Test

on:
  push:
    paths:
      - "runner/**"
      - "docker_test/**"
      - ".github/workflows/runner_test.yaml"

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: runner:dev
      BUILD_DIR: runner

    steps:
      - uses: actions/checkout@v2

      - name: Run PHP Test
        run: |
          cd docker_test/php    && docker build . -t php

      - name: Run Node Test
        run: |
          cd docker_test/php    && docker build . -t php

      - name: Run Python Test
        run: |
          cd docker_test/python && docker build . -t python
