name: Runner Test

on:
  push:
    paths:
      - "runner/**"
      - "docker_test/**"
      - ".github/workflows/runner_test.yaml"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Run PHP Test
        run: |
          docker build -f docker_test/php/Dockerfile . -t php

      - name: Run Node Test
        run: |
          docker build -f docker_test/node/Dockerfile . -t node

      - name: Run Python Test
        run: |
          docker build -f docker_test/python/Dockerfile . -t python
